apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-example-subject-headless
spec:
  replicas: 3
  selector:
    matchLabels:
      pass.subject: multi-example-subject-headless
  template:
    metadata:
      labels:
        pass.subject: multi-example-subject-headless
    spec:
      restartPolicy: Always
      containers:
        - name: subject-behavior
          image: multi_example_subject:latest
          imagePullPolicy: Never
          command: ["python", "/app/behavior.py"]
          env:
            - name: SUBJECT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROCESS_INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

        - name: input-pool
          image: input_pool:latest
          imagePullPolicy: Never
          command: ["input-pool"]

          env:
            - name: MAX_SIZE
              value: "10"
            - name: SENDER_LIMIT
              value: "10"
            - name: TYPE_LIMIT
              value: "5"
            - name: OVERFLOW_STRATEGY
              value: "BLOCK"

          ports:
            - containerPort: 8081
            - containerPort: 8080
